#%RAML 1.0 NamedExample
#healthcheckResponse
status: "active"
application: "weather-api"
env: "dev"
version: "v1"
systems:
- name: "Google API"
  status: "success"
  message: "Google API is up and running"