#%RAML 1.0 NamedExample
#weatherResponse
currentTempC: 24
currentTempF: 76
todayMaxTempC: 33
todayMaxTempF: 92
todayMinTempC: 24
todayMinTempF: 76
currentOutlook: "Partly Cloudy with Scattered Storms"